export const GET_ALL_MATCHES_REQUEST = 'GET_ALL_MATCHES_REQUEST ';
export const GET_ALL_MATCHES_SUCCESS = 'GET_ALL_MATCHES_SUCCESS ';
export const GET_ALL_MATCHES_FAILURE = 'GET_ALL_MATCHES_FAILURE ';

export const GET_SINGLE_MATCHES_DETAILS_REQUEST = 'GET_SINGLE_MATCHES_DETAILS_REQUEST ';
export const GET_SINGLE_MATCHES_DETAILS_SUCCESS = 'GET_SINGLE_MATCHES_DETAILS_SUCCESS ';
export const GET_SINGLE_MATCHES_DETAILS_FAILURE = 'GET_SINGLE_MATCHES_DETAILS_FAILURE ';
